// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3JWpchI6D1X7SSWP_6IR0RiXF7rtvspA',
    appId: '1:1091213606491:web:6296503ecd4bce08cd497e',
    messagingSenderId: '1091213606491',
    projectId: 'star-t-e93f5',
    authDomain: 'star-t-e93f5.firebaseapp.com',
    storageBucket: 'star-t-e93f5.firebasestorage.app',
    measurementId: 'G-J86DG0SFV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsvJCvi5PZgy1h8S5k_jvUj7PcKOll864',
    appId: '1:1091213606491:android:eebe2a3266211f81cd497e',
    messagingSenderId: '1091213606491',
    projectId: 'star-t-e93f5',
    storageBucket: 'star-t-e93f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfQuUixXPL7_30coECcY4HO1U_QJkxuOA',
    appId: '1:1091213606491:ios:817148470b165544cd497e',
    messagingSenderId: '1091213606491',
    projectId: 'star-t-e93f5',
    storageBucket: 'star-t-e93f5.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfQuUixXPL7_30coECcY4HO1U_QJkxuOA',
    appId: '1:1091213606491:ios:817148470b165544cd497e',
    messagingSenderId: '1091213606491',
    projectId: 'star-t-e93f5',
    storageBucket: 'star-t-e93f5.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3JWpchI6D1X7SSWP_6IR0RiXF7rtvspA',
    appId: '1:1091213606491:web:2f38f79ef8e0ab53cd497e',
    messagingSenderId: '1091213606491',
    projectId: 'star-t-e93f5',
    authDomain: 'star-t-e93f5.firebaseapp.com',
    storageBucket: 'star-t-e93f5.firebasestorage.app',
    measurementId: 'G-HNW5LFKD7Q',
  );
}
